version: "3.7"
services:
  remix:
    build:
      context: .
      args: 
        REMIX_AUTH: ${REMIX_AUTH}
    image: localhost:5000/blog:latest
    env_file:
    - .env
    ports:
      - 3000:3000
